before:
  hooks:
    - go mod tidy -compat=1.17
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - arm
      - amd64
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
