name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.17
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: imjasonh/setup-ko@v0.4
      - run: |
          ko publish --bare --platform=linux/amd64,linux/arm64,linux/arm/v5,linux/arm/v6,linux/arm/v7 \
          --tags=latest,$(git describe --tag --always --dirty) ./
